#### Consider the below code to answer further questions:
#### import numpy as np
#### list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
#### array_list = np.array(object = list_)

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

#### Q2. Write a code to print the data type of each and every element of both the variables list_ andarra_list.

#### Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_and arra_list.
#### Consider the below code to answer further questions:

#### import numpy as np
#### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#### num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:
#### (i) shape
#### (ii) size

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
#### [Hint: The size of the array will be 9 and the shape will be (3,3).]

#### Q6. Create an identity matrix of shape (5,5) using numpy functions?
#### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

####


## Answers

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
import numpy as np

In [4]:
list_ = [1,2,3,4,5,6]
array_list = np.array(object = list_)

In [5]:
array_list

array([1, 2, 3, 4, 5, 6])

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [6]:
type(list_)

list

In [7]:
type(array_list)

numpy.ndarray

#### list_ is a type of list variable but array_list is the type of ndarry

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [8]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [15]:
for i in array_list[0:7]:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_and arra_list.¶

In [16]:
array_list = np.array(object = list_, dtype = int)

In [17]:
array_list

array([1, 2, 3, 4, 5, 6])

In [19]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [22]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [24]:
num_array.size

6

In [25]:
num_array.shape

(2, 3)

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
### [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [33]:
import numpy.matlib as nm

In [37]:
arr=nm.zeros((3,3))
arr

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [38]:
arr=nm.eye(5)

In [39]:
arr

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])